### ISSUE TITLE
Variable enum fields

### ISSUE THREAD

**Issue by alexkazik** [creativcoder/clinews#2]
I don't think it's a good idea to have the enum change it's fields depending on features.

One could develop it for one feature, including a match on all errors, then switch the feature and now the code is broken.

You could use [non_exhaustive](https://doc.rust-lang.org/reference/attributes/type_system.html) to indicate that this enum may have more fields added in the future.

I'm aware that this is mostly a demo.

https://github.com/creativcoder/clinews/blob/dbb017462bf3e1e2f3e8e3a7f50a2e090512c298/newsapi/src/lib.rs#L21-L22

**Comment by creativcoder** [comment]
Yeah, great suggestion, thanks. Added a fix
